#! /bin/bash

if [[  $# -ne 1 || "$1" != "up" && "$1" != "down" ]]; then
	exit 1;
fi

curpath=/sys/class/backlight/intel_backlight/brightness

current=$(/usr/bin/cat $curpath)
max=$(/usr/bin/cat /sys/class/backlight/intel_backlight/max_brightness)

if [[ "$1" == "up" ]]; then
	new=$(python -c "print(int($current * 170 / 100))");
	if [[ $new -gt $max ]]; then
		echo $max > $curpath
	else
		echo $new > $curpath
	fi
fi	

if [[ "$1" == "down" ]]; then
	new=$(python -c "print(int($current * 60 / 100))");
	if [[ $new -gt 100 ]]; then
		echo $new > $curpath
	fi
fi	
