#! /bin/bash

curpath=/sys/class/backlight/intel_backlight/brightness
current=$(/usr/bin/cat $curpath)
max=$(/usr/bin/cat /sys/class/backlight/intel_backlight/max_brightness)

case "$1" in
 up)
    new=$(python -c "print(int($current * 170 / 100))")
    if [[ $new -gt $max ]]; then
    	echo $max > $curpath
    else
    	echo $new > $curpath
    fi
   ;;
 down)
    new=$(python -c "print(int($current * 60 / 100))")
    if [[ $new -gt 100 ]]; then
    	echo $new > $curpath
    fi
   ;;
 allowusers)
    # Allow members of users group to change brightness
    sudo chgrp users $curpath
    sudo chmod g+w $curpath
   ;;
 disallowusers)
    # Disallow members of users group to change brightness
    sudo chgrp root $curpath
    sudo chmod g-w $curpath
   ;;
 *)
    exit 1
   ;;
esac

exit 0
